// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTYcdlF3FC_Vp1OTCtN8IOSepxYcjdNhM',
    appId: '1:488437626321:android:b58c07a92b3b8f156fdcf0',
    messagingSenderId: '488437626321',
    projectId: 'todolist-9a495',
    storageBucket: 'todolist-9a495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzSKWycd3AGp3TMhvXLIce1GgkMTrsCK4',
    appId: '1:488437626321:ios:9298f20f732d23fa6fdcf0',
    messagingSenderId: '488437626321',
    projectId: 'todolist-9a495',
    storageBucket: 'todolist-9a495.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzSKWycd3AGp3TMhvXLIce1GgkMTrsCK4',
    appId: '1:488437626321:ios:9298f20f732d23fa6fdcf0',
    messagingSenderId: '488437626321',
    projectId: 'todolist-9a495',
    storageBucket: 'todolist-9a495.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkYyKW4unL9A0fnxgQloctCxuGPCl1m7E',
    appId: '1:488437626321:web:43ab112ae95f30396fdcf0',
    messagingSenderId: '488437626321',
    projectId: 'todolist-9a495',
    authDomain: 'todolist-9a495.firebaseapp.com',
    storageBucket: 'todolist-9a495.firebasestorage.app',
  );
}
